project:
  type: website
  output-dir: docs

website:
  title: "Übungen - VL: Statistik I"
  navbar:
    left:
      - href: index.qmd
        text: Übungen
      - href: about.qmd
        text: Hilfe & Kontakt
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Übung 1"
        href: exercise1.qmd
      #- text: "Übung 2"
      #  href: exercise2.qmd
  page-footer:
    left: "Copyright 2025, Gidon Frischkorn"
    right:
      - icon: github
        href: https://github.com/GidonFrischkorn

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

