---
title: "Übungen - VL: Statistik I"
subtitle: "HS 2025"
author: "Gidon Frischkorn"
---

Auf dieser Website finden Sie die Übungen zur Vorlesung "Statistik I" des Bachelors Psychologie an der Fakultät für Verhaltenswissenschaften und Psychologie der Universität Luzern. Die Übungen sind im Selbststudium parallel zur Vorlesung durchzuführen. Die Inhalte und Lösungen der Übungen gehören wie der Inhalt der Vorlesung selbst zum Prüfungsstoff.

In der Regel dauert die Lösung einer Übung für eine Vorlesung zwischen 90 und 120 Minuten. Inhalte der Übungen sind neben vertiefenden Inhalten, wie zum Beispiel Videos oder Online-Artikeln, Aufgaben mit der Statistik Software R.

## Einrichtung von R & RStudio auf ihrem PC / Laptop

### R

Ich empfehle Ihnen direkt zum Start des Semester die Statistik-Software R auf Ihrem PC oder Laptop zu installieren. Für Windows folgen sie dafür bitte diesem Link: <https://cran.r-project.org/bin/windows/base/> und für Mac bitte diesem Link: <https://cran.r-project.org/bin/macosx/>. Auf neueren Mac Rechnern müssen sie in der Regel die ARM-Version für Mac installieren. Diese ist für Chipsätze der M-Generationen (M1 / M2 / M2 Pro / etc.) optimiert.

R selbst ist keine Software sondern eine Programmiersprache ähnlich wie C, C++, oder JavaScript. Die üblichen R Pakete installieren zwar auch ein Graphical User Interfance (GUI) zur Nutzung von R. Dennoch ist die Verwendung einer Integrated Developer Environment (IDE) empfehlenswert um effizient und strukturiert mit R arbeiten zu können.

### R Studio

Nachdem Sie R installiert haben, empfehle ich Ihnen R Studio als "Integrated Developer Environment" (IDE) zu installieren. R Studio können sie unter dem folgenden Link herunterladen: <https://posit.co/download/rstudio-desktop/>
